15.0 academy module creation axlongines
axlongines/practice pull request #1
Opened 2022-07-27 18:29 UTC by axlongines

**This pr contains the exercise of creation of module, also implements the following views**

- tree view for the main view
- editing, deleting, creating form view

2022-07-27 19:33 UTC, axlongines commented
hi @edy1192, could you review plis :3 ?

2022-07-27 20:33 UTC, edy1192 requested changes

2022-07-27 20:33 UTC, edy1192 commented on .vscode/settings.json
> +{
Remove this file and the .vscode folder please.

2022-07-27 20:33 UTC, edy1192 commented on README.rst
> +*Readme of the tecnical course*
Please add some description.

2022-07-27 20:33 UTC, edy1192 commented on controllers/controllers.py
>  # from odoo import http
Please don't add commented code. Remove this file and all the references to it. When you need this you'll add it.

2022-07-27 20:33 UTC, edy1192 commented on controllers/__init__.py
> +from . import controllers
Remove this file also remove the controllers folder. When you need this you'll add it.

2022-07-27 20:33 UTC, edy1192 commented on __init__.py
>  from . import controllers
Remove this import please. Don't need controllers.

2022-07-27 20:33 UTC, edy1192 commented on __manifest__.py
> +    "depends": ["base"],
```suggestion
    "depends": [
    "base",
    ],
```

2022-07-27 20:33 UTC, edy1192 commented on __manifest__.py
> +        "views/course_menu_view.xml",
Please rename the files. See [guideline](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming) for file naming please.

2022-07-27 20:33 UTC, edy1192 commented on __manifest__.py
> +    "demo": ["demo/course.xml"],
```suggestion
    "demo": [
    "demo/course.xml"
    ],
```

Please rename the file. See [guideline](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming) for file naming please.

2022-07-27 20:33 UTC, edy1192 commented on models/models.py
> -# -*- coding: utf-8 -*-
Please don't add commented code. Remove this file and all the references to it.

2022-07-27 20:33 UTC, edy1192 commented on models/__init__.py
> +from . import models
Remove this please.

2022-07-27 20:33 UTC, edy1192 commented on models/course.py
> +from odoo import models, fields
Please rename the file. See [guideline](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming) for file naming please.

2022-07-27 20:33 UTC, edy1192 commented on models/course.py
> +class Course(models.Model):
Class name same as model please.

```suggestion
class OpenAcademyCourse(models.Model):
```

2022-07-27 20:33 UTC, edy1192 commented on security/ir.model.access.csv
> +access_open_academy_model_course,access_open_academy_model_course,model_course,base.group_user,1,1,1,1
Model's name is wrong. Your model is open.academy.course.

```suggestion
access_open_academy_model_course,access_open_academy_model_course,model_open_academy_course,base.group_user,1,1,1,1
```

2022-07-27 20:33 UTC, edy1192 commented on demo/course.xml
> +        <record id="react_course" model="open.academy.ourse">
```suggestion
        <record id="open_academy_course_react_demo" model="open.academy.course">
```

See [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#254demo-records) to name and xml_id and apply it to all the ids in this file please.

2022-07-27 20:33 UTC, edy1192 commented on demo/demo.xml
> +</odoo>
Do not add empty files. Please remove this.

2022-07-27 20:33 UTC, edy1192 commented on views/course_menu_view.xml
> +    <menuitem id="list_menu_courses"  name="Courses" sequence="2" action="open_academy_course_action"/>
Plase add a root menu for the module.

```suggestion
    <menuitem id="open_academy_root_menu" name="Open Academy" sequence="1"/>
    <menuitem id="open_academy_course_menu"  name="Courses" sequence="1" action="open_academy_course_action" parent="open_academy_root_menu"/>
```
And see the [guideline](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#252security-view-and-action) to name views and menus

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +    <record model="ir.ui.view" id="open_academy_course_view_action">
This is not an action. The standard for naming views is <model_name>_view_<view_type> , where view_type is kanban, form, tree, search

```suggestion
    <record model="ir.ui.view" id="open_academy_course_view_tree">
```
See the [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#252security-view-and-action) please. And apply this to all records in this file please.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +        <field name="name">List courses</field>
The view name is the same as id but separated by .
```suggestion
        <field name="name">open.academy.course.view.tree</field>
```

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +        <field name="res_model">course</field>
You need to try your changes, this should cause an error when updating the module. Your model name is "open.academy.course"

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +        <field name="model">course</field>
You need to try your changes, this should cause an error when updating the module. Your model name is "open.academy.course"

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +                <field name="title" string="Courses" />
String attibute is not necessary in tree views.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +                <field name="description" string="Description" />
Same here.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +    <record model="ir.ui.view" id="open_academy_course_form_action">
Rename id please.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +        <field name="name">form courses</field>
Rename form view.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +        <field name="model">course</field>
Check your model name.

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +                <sheet string="Form course">
```suggestion
                <sheet string="Course">
```

2022-07-27 20:33 UTC, edy1192 commented on views/course_view.xml
> +                            </group>
The exercise only asks to add the description field to the page. Please remove the title field from here and add it outside the page.

2022-07-27 20:33 UTC, edy1192 commented on views/templates.xml
> -</odoo>
Remove this file please.

2022-07-27 20:33 UTC, edy1192 commented on views/views.xml
> -</odoo>
Remove this file please.

2022-07-27 20:34 UTC, edy1192 commented
@AxelRuLo please change the PR's title. 

Use the commit's title please.

2022-07-29 15:50 UTC, edy1192 requested changes
Please remove the controllers folder, is empty right now.

2022-07-29 15:50 UTC, edy1192 commented on views/open_academy_course_views.xml
> +
Just one blank line please.

2022-07-29 15:51 UTC, edy1192 commented
> @AxelRuLo please change the PR's title.
> 
> Use something like this:
> 
> [ADD] open_academy: new module to manage an academy

This change is pending.

I meant this

![image](https://user-images.githubusercontent.com/11479473/181797128-c914d72c-c810-4c09-adac-9ff87b5e2372.png)

2022-07-29 15:52 UTC, edy1192 commented
@AxelRuLo please squash the commits. Just one commit please.

2022-07-29 15:55 UTC, edy1192 commented
@AxelRuLo please squash the commits. Just one commit please.

2022-07-29 17:12 UTC, edy1192 approved these changes

2022-07-29 17:13 UTC, edy1192 commented
@axlongines I don't know if something happens that I keep seeing the controllers folder. I'm going to merge the PR and if that folder is still there, please delete it in the next PR.

2022-07-29 17:14 UTC, merged